import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { scoreToScale } from '../config/institutionTypes';

export function generateReportCardPDF({ institution, student, grades, typeConfig }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(20, 24, 43); // ink
  doc.rect(0, 0, pageWidth, 90, 'F');
  doc.setTextColor(246, 241, 231); // sand
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(institution?.name || 'CampusIQ Africa', 40, 38);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(typeConfig.reportCardTitle, 40, 56);
  doc.setFontSize(9);
  doc.text(`${institution?.country || ''}  ·  ${institution?.academic_year || ''}`, 40, 72);

  doc.setTextColor(20, 24, 43);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`${student.first_name} ${student.last_name}`, 40, 118);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Matricule: ${student.matricule || '—'}`, 40, 132);
  doc.text(`${typeConfig.classTerm}: ${student.class_program_id || '—'}`, 40, 144);

  const rows = grades.map((g) => {
    const scaled = scoreToScale(g.score, g.max_score, institution?.type);
    return [g.subject_course, g.assessment_type, g.term, `${g.score}/${g.max_score}`, scaled.formatted, g.comments || ''];
  });

  autoTable(doc, {
    startY: 165,
    head: [['Subject / Course', 'Assessment', 'Term', 'Raw score', typeConfig.gradeTerm, 'Comments']],
    body: rows,
    headStyles: { fillColor: [199, 93, 59], textColor: 255, fontSize: 8.5 },
    bodyStyles: { fontSize: 8.5 },
    margin: { left: 40, right: 40 },
  });

  const avgScaled = grades.length
    ? grades.reduce((sum, g) => sum + scoreToScale(g.score, g.max_score, institution?.type).value, 0) / grades.length
    : 0;

  const finalY = doc.lastAutoTable.finalY + 24;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(`Overall ${typeConfig.gradeTerm}: ${typeConfig.scoreScale.format(Math.round(avgScaled * 100) / 100)}`, 40, finalY);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(91, 96, 114);
  doc.text(`Generated by CampusIQ Africa on ${new Date().toLocaleDateString()}`, 40, finalY + 30);

  doc.save(`${student.last_name}_${student.first_name}_report_card.pdf`);
}
